version: '3'
services:
  spotify:
    image: satishjagana/spotifyv1:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3

  zomato:
    image: satishjagana/zomatov1:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3

  swiggy:
    image: satishjagana/swiggyv1:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3

  
