version: '3'
services:
  spotify:
    image: satishjagana/spotifyv1:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  zomato:
    image: satishjagana/zomatov1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  swiggy:
    image: satishjagana/swiggyv1:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  
